- name: "Creates directory"
  file:
    path: "~/server"
    state: "directory"
    mode: 0755

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/server

- name: "Run the web server"
  shell:
    cmd: |
      cd ~/server
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready
